[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m/scratch/06040/adcruz/pyscripts/CGM_SIDM/HIClumps_2022/scripts/run_pyfof_clump_data.py:1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyfof_HI_clumps[39;00m
[1;32m      2[0m model    [38;5;241m=[39m [38;5;124m'[39m[38;5;124mh148_6144[39m[38;5;124m'[39m 
[1;32m      3[0m output   [38;5;241m=[39m [38;5;124m'[39m[38;5;124m003456[39m[38;5;124m'[39m

File [0;32m/scratch/06040/adcruz/pyscripts/CGM_SIDM/HIClumps_2022/scripts/pyfof_HI_clumps.py:3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m 
[1;32m      2[0m [38;5;66;03m#import yt [39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyfof[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mrandom[39;00m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mpynbody[39;00m

[0;31mModuleNotFoundError[0m: No module named 'pyfof'
